name: SwiftLint starter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
